sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -t swatis1209s/docker-react -f Dockerfile.dev .

# -e CI =true is used to automatically terminate test suite execution once its over
script:
    - docker run -e CI=true swatis1209s/docker-react npm run test